apiVersion: v1
kind: Service
metadata:
  name: hera-webhook-server
  namespace: hera-namespace
  labels:
    app: hera-webhook-server
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
  selector:
    app: hera-webhook-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hera-webhook-server
  namespace: hera-namespace
spec:
  selector:
    matchLabels:
      app: hera-webhook-server
  replicas: 1
  template:
    metadata:
      labels:
        app: hera-webhook-server
    spec:
      volumes:
        - name: hera-webhook-tls-sh-volume
          configMap:
            name: hera-webhook-server-p12
      containers:
        - name: hera-webhook-server
          image: herahub/opensource-pub:hera-webhook-server-v2-6
          env:
            - name: LOG_AGENT_POD_CONDITION_POD_PREFIX
              value: hera-demo
            - name: LOG_AGENT_VOLUME_MOUNTS_NAME
              value: log-path,app-logs
            - name: LOG_AGENT_CONDITION_NAMESPACE
              value: hera-namespace
          volumeMounts:
            - name: hera-webhook-tls-sh-volume
              mountPath: /tmp/hera-webhook-server-p12
      serviceAccountName: admin-mone